# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bc70fe7880c2f7e02f327503920371321d295586ec3f9c1dc0a2947c351a225d912ebdd1ebcd98255b1db773b50627f314ea8906ac28fee484fc6f965d98450e

test:
  secret_key_base: 19ceccc89e812b43d60843c41a25a986b706a9b82795d4c455610babed6d1ea86f14c63c91cf72af56ae053bdb6438539ff22a93bee09d8bc705ee86f7b07dc0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
